# Required environment variables
# ------------------------------
# The following must be configured in the Travis settings control panel:
#
# RELEASE_OAUTH_TOKEN (GitHub) with `repo` and `push` scopes

language: clojure
lein: 2.9.8
arch: amd64

dist: bionic
services:
  - xvfb

jdk:
  - openjdk8

env:
  global:
  - ARTIFACTS_DIR=~/$TRAVIS_BUILD_NUMBER
  - TEMP_DIR=~/$TRAVIS_BUILD_NUMBER

cache:
  directories:
    - $HOME/.m2

script:
  - lein jar

deploy:
  # DEPLOY to GitHub (when tagged)
  - provider: releases
    api_key: $RELEASE_OAUTH_TOKEN
    file_glob: true
    file: target/grafter-db-*.jar
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$